development:
  adapter: postgresql
  encoding: unicode
  database: angelia_development

test:
  adapter: postgresql
  encoding: unicode
  database: angelia_test

production:
  adapter: postgresql
  encoding: unicode
  database: angelia_production
